# Generated by Django 3.1.5 on 2021-01-09 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'catogries',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categories', models.CharField(max_length=30)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.categories')),
            ],
            options={
                'db_table': 'sub_catogries',
            },
        ),
    ]
